README.md | Add libraspberrypi-dev to as RPi-specific build dependency
Due to:
```
g++ -mcpu=arm1176jzf-s -mfpu=vfp -Ofast -pipe -Wno-shift-overflow -Wno-narrowing  -std=gnu++14 -MD -MT src/inputdevice.o -MF src/inputdevice.d -DARMV6_ASSEMBLY -D_FILE_OFFSET_BITS=64 -DARMV6T2 -DUSE_DISPMANX -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads  -I/usr/local/include/SDL2 -D_REENTRANT -Iexternal/libguisan/include -Isrc -Isrc/osdep -Isrc/threaddep -Isrc/include -Isrc/archivers -I/usr/include/libxml2 -DAMIBERRY  -c -o src/inputdevice.o src/inputdevice.cpp
In file included from src/inputdevice.cpp:39:
src/osdep/amiberry_gfx.h:5:10: fatal error: bcm_host.h: No such file or directory
 #include <bcm_host.h>
          ^~~~~~~~~~~~
compilation terminated.
```

Signed-off-by: MichaIng <micha@dietpi.com>